import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import AuthProvider from '@/context/authProvider'
import NavBar from "@/components/message/NavBar";
import SidBar from "@/components/message/SidBar";
import SendMessage from "@/components/message/send-message";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        
      <body className={inter.className}>
        {/* <NavBar/> */}
        <div className="flex">
        <SidBar/>
        <div className="bg-blue-800 w-full">
          <NavBar/>
        {children}
        {/* <SendMessage/> */}
        </div>
        
        </div>
        </body>
      </AuthProvider>
    </html>
  );
}
