import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import SideBar from "@/components/Chat/SideBar";
import AuthProvider from "@/context/authProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        <body className={inter.className}>
          {/* <NavBar/> */}
          <div className="">
            <SideBar />
            {children}
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
